config/routes.rb
Rails.application.routes.draw do
  
  resources :movies

  post "/movies/:id/reviews", to: "reviews#create", as: :reviews


  devise_for :users
  root to: "movies#index"
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews

  has_attached_file :movie_cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing_movie.png"
  validates_attachment_content_type :movie_cover, :content_type => /\Aimage\/.*\Z/

  validates :title, :body, :year, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :comment, presence: true
  validates :rating, presence: true,
                     inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :reviews

  validates :first_name, :last_name, presence: true
  validates :username, presence: true, uniqueness: true


  def full_name
    first_name + last_name
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :danger
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :first_name, :last_name]
    devise_parameter_sanitizer.for(:account_update) << :avatar
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = @movie.reviews
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, success: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, success: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :body, :year, :run_time, :movie_cover)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def create
    @movie = Movie.find(params[:id])
    @review = @movie.reviews.new(review_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @review.save
        format.html { redirect_to movie_path(@movie), notice: 'Review was successfully created.' }
      else
        format.html { redirect_to movie_path(@movie), error: 'Sorry, something went wrong.' }
      end
    end
  end



  private
    def review_params
      params.require(:review).permit(:comment, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenPotatoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rotten Potatoes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Movies", movies_path %></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li><a href="#">????</a></li>
            <li><a href="#">????</a></li>
            <li class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>  
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong><%= type.humanize %>!</strong> <%= message %>
  </div>
<% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie, :html => { :multipart => true }) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :run_time %><br>
    <%= f.text_field :run_time %>
  </div>


    <%= f.file_field :movie_cover %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Year</th>
      <th>Run time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.body %></td>
        <td><%= movie.year %></td>
        <td><%= movie.run_time %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @movie.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-2 text-center">
    <%= image_tag @movie.movie_cover.url(:medium), class: "img-responsive" %>
    <%= link_to raw('<i class="fa fa-pencil-square"></i> Edit'), edit_movie_path(@movie), class: "btn btn-warning btn-block" %>
    <%= link_to raw('<i class="fa fa-arrow-left"></i> Back'), movies_path, class: "btn btn-primary btn-block" %>
  </div>

  <div class="col-xs-10">
    <p>
      <strong>Year:</strong>
      <%= @movie.year %>
      <strong>Run time:</strong>
      <%= @movie.run_time %>
    </p>

    <p>
      <%= @movie.body %>
    </p>

    <h2><i class="fa fa-comments"></i> Reviews</h2>
    <%= form_for(Review.new, url: reviews_path) do |f| %>
      <div class="form-group">
        <%= f.label :comment, "Please review the movie" %><br>
        <%= f.text_area :comment, rows: 4, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :rating %><br>
        <%= f.number_field :rating, default: 0, in: 0..5, class: "form-control" %>
      </div>

      <%= f.submit "Save Review", class: "btn btn-success" %> 
    <% end %>
    <ul class="media-list">
    <% @reviews.each do |review| %>
      <li class="media">
        <div class="media-left media-top">
          <a href="#">
            <%= image_tag(review.user.avatar.url(:thumb), class: "media-object") %>
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= review.user.first_name %> <%= review.user.last_name %></h4>
          <p><strong>Rating: <%= review.rating %></strong></p>
          <p><%= review.comment %></p>
        </div>
      </li>
    <% end %>
    </ul>


  </div>
</div>
<!-- INSERT REVIEWS -->